# ignore path during linting
excluded:
  - Pods
  - kfm-ios-testTests
  - kfm-ios-testUITests

disabled_rules:
  - trailing_whitespace

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 200
  error: 400

type_name:
  allowed_symbols: ["_"]
  min_length:
    warning: 4
  max_length:
    warning: 40
    error: 50

identifier_name:
  excluded:
    - ok
    - id
    - url
    - app
  min_length:
    warning: 4
  max_length:
    warning: 40
    error: 50

line_length:
  warning: 200
  error: 400

opt_in_rules:
  - force_unwrapping
  - conditional_returns_on_newline
  - private_outlet
  - vertical_whitespace

reporter: "xcode"
